name: CI/CD Pipeline

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Define the jobs to run
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Verify existence of example.txt
      run: |
        if grep -q "Hello Shivam" example.txt; then
          echo "text exists in example.txt"
        else
          echo "text does not exist in example.txt"
          exit 1
        fi
